/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w8Roqs5CeKXUVajBnjnyHA

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsb57XETfIhysw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: B57xETfIhysw/globalVariant
import { useScreenVariants as useScreenVariantsqmLtHiTXdNxv } from "../fragment_design_system/PlasmicGlobalVariant__Screen"; // plasmic-import: QmLtHiTXdNxv/globalVariant
import { useScreenVariants as useScreenVariantsbr2UhI7UlpvR } from "../fragment_icons/PlasmicGlobalVariant__Screen"; // plasmic-import: BR2UhI7ulpvR/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsb57XETfIhysw,
  screen: useScreenVariantsqmLtHiTXdNxv,
  screen: useScreenVariantsbr2UhI7UlpvR
});
